# Generated by Django 3.1.4 on 2021-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witryna', '0002_presentevent_shuffled'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='giver',
            field=models.CharField(default='nie podano', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='taker',
            field=models.CharField(default='nie podano', max_length=20),
        ),
    ]
